### ISSUE TITLE
header

### ISSUE THREAD

**Issue by hoseinsalehi** [dvictori/flux2nc#7]
Hello sir.
I want to use your script to convert ASCII files of VIC.4.2.d to NetCDF format.
can you help me to this permission.
I need a tutorial for this.

**Comment by dvictori** [comment]
Dear Hoseinsalehi,

As I explained in the Readme, I wrote this script quite some time ago. You are free to use it and modify as needed but unfortunately I don't have the time right now to make any changes or bug fixes.

I still need to write better instructions for the script but basically, all you need to run this script is a working python + numpy + scipy install. Then, just run the script, indicating the folder were the VIC flux files are located and answer the questions that appear on the screen.
